version: 0.2
phases:
  install:
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - envsubst < .env.template > .env
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:node -f "Dockerfile" .
      - docker build -t $REPOSITORY_URI:nginx -f "nginx.Dockerfile" .
      - docker tag $REPOSITORY_URI:node $REPOSITORY_URI:node-$IMAGE_TAG
      - docker tag $REPOSITORY_URI:nginx $REPOSITORY_URI:nginx-$IMAGE_TAG
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:node-$IMAGE_TAG
      - docker push $REPOSITORY_URI:nginx-$IMAGE_TAG
      - printf 'export NGINX_IMAGE=%s\nexport PHP_IMAGE=%s' $REPOSITORY_URI:nginx-$IMAGE_TAG $REPOSITORY_URI:node-$IMAGE_TAG > imageDetail.sh
      
artifacts:
  files:
    - '**/*'












